public class Primitivedata_Assigment {
    public void PrimitivedataAssigmentMethod() {

        Id accountID = '0018d00000KUibPAAT';
        String text1= 'The folloing Id belongs to Accounts';
        String accountName = 'GenePoints';
        Boolean IsItLow = true ;

        System.debug('Account ID --> ' + accountID);
        System.debug('Account Name is  ' + accountName);
        System.debug(IsItLow);
        System.debug('Account ID =  ' + accountID + '  Account Name is  ' + accountName + ' ' +  IsItLow);


    }
}
