PrimitiveDataType2 p2 = new PrimitiveDataType2();
p2.printNewDate();
p2.printTime();
p2.printNewDateTime();

String firstName ='Berrin';
String lastName ='Çayırlı';
String fullName = firstName + ' ' + lastName;
System.debug(fullName);

String brand = 'VolksWagen';
System.debug(brand);
String model = 'Tiguan';
System.debug(model);
String color = 'Grey';
System.debug(color);
String mycar = 'My Car is ' + brand + ' ' + model +  ' ' + color ;
System.debug(mycar);