public class ArthimaticCalculations {

    
    public void Addition(Integer x, Integer y) {
        Integer z = x +  y;
        System.debug('sum: ' + z);
    }


    public void Subtraction(Integer x, integer y){
        Integer z = x - y;
        System.debug(' subt: ' + z);
    }



    public void Multiplcation(Integer x, integer y, Integer m){
        Integer z = x * y * m;
        System.debug(' Multp: ' + z);
    }
}
