public class SalesforceDeveloper {
    public void myFirstCode() {
        String city = 'Istanbul';
        System.debug('My favorite City is '+ city);
        String film = 'Hayat güzeldir';
        system.debug('My favorite Film is ' + film);
        String season = 'Summer';
        System.debug('My favorite season is ' + season);


        String mycity = 'Isparta';
        System.debug(mycity);
        Integer fvrtno = 2;
        System.debug(fvrtno);
        System.debug('My favorite number --> ' + fvrtno + '  and  My city is  ' + mycity);
    }
    
}